POST http://localhost:5002/post/add
Content-Type: application/json

{
    "post_id":"kill-animal",
    "user_id":"1qasas2sa",
    "name":"animals",
    "title":"The Lion King",
    "content":"The lion is a species in the family Felidae and a member of the genus Panthera. It is most recognisable for its muscular, deep-chested body, short, rounded head, round ears, and a hairy tuft at the end of its tail. It is sexually dimorphic; adult male lions have a prominent mane",
    "mime_type":"txt",
    "status":"1",
    "post_status":"1",
    "post_count":0,
    "post_parent":"",
    "meta":[]
}
###

POST http://localhost:5002/comment/add
Content-Type: application/json

{
    "post_id":"the-lion-king",
    "user_id":"1qasas2sa",
    "author":"animals",
    "author_email":"anaymous@mail.com",
    "content":"Lions do do not go wating and whating around aimlessly, so how do you rate them",
    "author_ip":"129.0.0.1",
    "author_url":"",
    "content_type":"txt",
    "meta":[]
}
###
GET http://localhost:5002/post/findAll
###
GET http://localhost:5002/post/s/the-lion-king


###
GET http://localhost:5002/comment/the-lion-king